//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCK_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adhesion
    {
        public int idAnnonce { get; set; }
        public int idUtilisateur { get; set; }
        public Nullable<int> nbSlot { get; set; }
    
        public virtual Annonce Annonce { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
