//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCK_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annonce
    {
        public int idAnnonce { get; set; }
        public Nullable<int> idCategorie { get; set; }
        public string titre { get; set; }
        public string description { get; set; }
        public Nullable<int> nbSlot { get; set; }
        public Nullable<int> nbSlotUtilise { get; set; }
        public Nullable<bool> estActive { get; set; }
        public Nullable<int> idUtilisateur { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
