//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCK_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int idMessage { get; set; }
        public Nullable<int> idExpediteur { get; set; }
        public Nullable<int> idDestinataire { get; set; }
        public Nullable<System.DateTime> dateEnvoi { get; set; }
        public string message { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Utilisateur Utilisateur1 { get; set; }
    }
}
