//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCK_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscription
    {
        public int idUtilisateur { get; set; }
        public int idVoyage { get; set; }
        public Nullable<bool> estHebdomadaire { get; set; }
        public Nullable<bool> estQuotidien { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Voyage Voyage { get; set; }
    }
}
