//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCK_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rencontre
    {
        public int idRencontre { get; set; }
        public Nullable<int> idDemander { get; set; }
        public Nullable<int> idDemandeur { get; set; }
        public Nullable<bool> aAccepteDemander { get; set; }
        public Nullable<bool> aAccepteDemandeur { get; set; }
        public Nullable<int> idVoyage { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Utilisateur Utilisateur1 { get; set; }
    }
}
