//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCK_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voyage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voyage()
        {
            this.Inscriptions = new HashSet<Inscription>();
        }
    
        public int idVoyage { get; set; }
        public string depart { get; set; }
        public string arrivee { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> horaireArrivee { get; set; }
        public Nullable<System.TimeSpan> horaireDepart { get; set; }
        public Nullable<int> numeroTrain { get; set; }
        public Nullable<int> nbWagon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscription> Inscriptions { get; set; }
    }
}
